version: '3'

services:
    db:
      image: postgres
      container_name: cmsapidatabase
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: cms
        POSTGRES_PASSWORD: CMS
      restart: always
      command: ["postgres", "-c", "log_statement=all"]
    cmsapp:
      build: .
      container_name: cmsapi
      ports:
       - 3000:3000
      environment:
        POSTGRES_HOST: db
      links: 
       - db

